import Head from "next/head";
import { Slideshow } from "../components/Slideshow";

export default function Home() {
	return (
		<div>
			<Head>
				<title>serendipity</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>Serendipity</h1>
			<Slideshow slides={[1, 2, 3, 4, 5, 6, 7, 8]} initialIndex={0} />
		</div>
	);
}
