import Head from "next/head";
import create from "zustand";
import { exampleSlides } from "../components/SlideEditor/exampleSlides";
import { SlideEntity } from "../components/SlideEditor/SlideEntity";
import { Slideshow } from "../components/Slideshow";

export const useSlideStore = create<{ slides: SlideEntity[][] }>(() => ({
	slides: exampleSlides,
}));

export default function Home() {
	const { slides } = useSlideStore();
	return (
		<div>
			<Head>
				<title>hyperslide</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>hyperslide</h1>
			<Slideshow slides={slides} initialIndex={0} />
		</div>
	);
}
