import Head from "next/head";
import { exampleSlides } from "../components/SlideEditor/exampleSlides";
import { Slideshow } from "../components/Slideshow";

export default function Home() {
	return (
		<div>
			<Head>
				<title>serendipity</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>Serendipity</h1>
			<Slideshow slides={exampleSlides} initialIndex={0} />
		</div>
	);
}
